name: Deploy Production Bazaar

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Chrckout repo
        uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./gradlew assembleBazaarRelease appDistributionUploadBazaarRelease
